spring:  
  jpa:  
    hibernate:  
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties: 
      hibernate:  
        jdbc:
          lob:
            # Fix java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented
            non_contextual_creation: true
  datasource:  
    url: "jdbc:postgresql://localhost:5432/pgdb"  
    username: pguser  
    password: pgpass
