# Web
server:
  port: 8080
  servlet:
    contextPath: "/api"

# Spring
spring:  
  jpa:  
    hibernate:  
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties: 
      hibernate:
        # Fix java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented  
        jdbc.lob.non_contextual_creation: true
  datasource:  
    url: "jdbc:postgresql://localhost:5432/aphdb"  
    username: aphuser  
    password: aphpass
  data:
    # default is application/hal+json
    rest.defaultMediaType: application/json    
  flyway:
    locations: filesystem:db/migration
    
# lOGGING
logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    
---
spring:
  profiles: generatesql
  datasource:
    url: jdbc:postgresql://localhost:5432/aphdb
    username: aphuser  
    password: aphpass
  flyway:
    enabled: false
  jpa:
    properties:
      javax: 
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: src/main/resources/ddl_jpa_creation.sql    