# Web
server:
  port: 9090
  servlet:
    contextPath: "/api"

# Spring
spring:  
  datasource:  
    url: "jdbc:postgresql://localhost:5432/aphdb"  
    username: aphuser  
    password: aphpass
  jpa:  
    hibernate:  
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties: 
      hibernate:
        # Fix java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented  
        jdbc.lob.non_contextual_creation: true
  data:
    # default is application/hal+json
    rest.defaultMediaType: application/json
  flyway:
    locations: filesystem:db/migration
    enabled: false
  jackson:     
    serialization: 
      FAIL_ON_EMPTY_BEANS: false
    
# lOGGING
logging:
  level:
    # In development view sql
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
   
# -- Required for multiple profiles in file 
---
spring:
  profiles: sqlgen
  datasource:
    url: jdbc:postgresql://localhost:5432/aphdb
    username: aphuser  
    password: aphpass
  jpa:
    properties:
      javax: 
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: db/ddl_jpa_creation.sql
  flyway:
    enabled: false

---
spring:  
  profiles: dbgen
  datasource:  
    url: "jdbc:postgresql://localhost:5432/aphdb"  
    username: aphuser  
    password: aphpass
  jpa:  
    hibernate:  
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties: 
      hibernate:
        jdbc.lob.non_contextual_creation: true
  data:
    rest.defaultMediaType: application/json
  flyway:
    enabled: false
    