-- DROP TABLE HABITACION;
-- DROP TABLE HOTEL;

CREATE TABLE HOTEL (
	ID_HOTEL BIGINT NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	DIRECCION VARCHAR(100) NOT NULL,
	TELEFONO VARCHAR(100) NOT NULL,
	DESCRIPCION VARCHAR(100),
	LOCALIDAD VARCHAR(30),
	HOTEL_CATEGORIA VARCHAR(30)
);

CREATE TABLE HABITACION (
	ID_HABITACION BIGINT NOT NULL,
	ID_HOTEL BIGINT NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	NUM_PISO INTEGER NOT NULL,
	HABITACION_TIPO VARCHAR(30),
	NUM_PERSONAS INTEGER
);
