
/*
DROP TABLE HABITACION;
DROP TABLE HOTEL;
DROP TABLE HABITACION_TIPO;
DROP TABLE HOTEL_CATEGORIA;
DROP TABLE LOCALIDAD;
DROP TABLE REGION;
DROP SEQUENCE LOCALIDAD_ID_SEQ;
DROP SEQUENCE REGION_ID_SEQ;
*/

CREATE TABLE HABITACION_TIPO (
    ID BIGSERIAL NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    NUM_PERSONAS INT NOT NULL
);
ALTER TABLE HABITACION_TIPO ADD CONSTRAINT HABITACION_TIPO_PK PRIMARY KEY (ID);


CREATE TABLE HOTEL_CATEGORIA (
    ID BIGSERIAL NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL
);
ALTER TABLE HOTEL_CATEGORIA ADD CONSTRAINT HOTEL_CATEGORIA_PK PRIMARY KEY (ID);


CREATE TABLE PAIS (
    ID BIGSERIAL NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL
);
ALTER TABLE PAIS ADD CONSTRAINT PAIS_PK PRIMARY KEY (ID);


CREATE TABLE CIUDAD (
    ID BIGSERIAL NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    ID_PAIS BIGINT NOT NULL
);
ALTER TABLE CIUDAD ADD CONSTRAINT CIUDAD_PK PRIMARY KEY (ID);

CREATE TABLE HOTEL (
	ID BIGSERIAL NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	DIRECCION VARCHAR(100) NOT NULL,
	TELEFONO VARCHAR(100) NOT NULL,
	DESCRIPCION VARCHAR(100),
	ID_CIUDAD BIGINT NOT NULL,
	ID_HOTEL_CATEGORIA BIGINT NOT NULL
);
ALTER TABLE HOTEL ADD CONSTRAINT HOTEL_PK PRIMARY KEY (ID);


CREATE TABLE HABITACION (
	ID BIGSERIAL NOT NULL,	
	NUMERO VARCHAR(10) NOT NULL,
	PISO INTEGER NOT NULL,
	ID_HOTEL BIGINT NOT NULL,
    ID_HABITACION_TIPO BIGINT NOT NULL
);
ALTER TABLE HABITACION ADD CONSTRAINT HABITACION_PK PRIMARY KEY (ID);

ALTER SEQUENCE HABITACION_TIPO_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE HOTEL_CATEGORIA_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE PAIS_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE CIUDAD_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE HOTEL_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE HABITACION_ID_SEQ RESTART WITH 1000;

-- FOREIGN KEYS
ALTER TABLE CIUDAD ADD CONSTRAINT CIUDAD_FK_PAIS FOREIGN KEY (ID_PAIS) REFERENCES PAIS (ID);
ALTER TABLE HOTEL ADD CONSTRAINT HOTEL_FK_HOTEL_CATEGORIA FOREIGN KEY (ID_HOTEL_CATEGORIA) REFERENCES HOTEL_CATEGORIA (ID);
ALTER TABLE HOTEL ADD CONSTRAINT HOTEL_FK_CIUDAD FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD (ID);
ALTER TABLE HABITACION ADD CONSTRAINT HABITACION_FK_HOTEL FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL (ID);
ALTER TABLE HABITACION ADD CONSTRAINT HABITACION_FK_HABITACION_TIPO FOREIGN KEY (ID_HABITACION_TIPO) REFERENCES HABITACION_TIPO (ID);


------------------------------
-- DEMO

CREATE TABLE DEMO (
	ID BIGSERIAL NOT NULL,
	OBID UUID NOT NULL, 
	NOMBRE VARCHAR(100) NOT NULL,
	ID_CIUDAD BIGINT NOT NULL
);
ALTER TABLE DEMO ADD CONSTRAINT DEMO_PK PRIMARY KEY (ID);
ALTER TABLE DEMO ADD CONSTRAINT DEMO_FK_CIUDAD FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD (ID);
ALTER SEQUENCE DEMO_ID_SEQ RESTART WITH 1000;
