name: Proof

on:
  push:
    branches: 
      - develop

jobs:
  deploy:
    name: Tools
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Check Version
      run: |
        java -version
        mvn -version
        aws --version
        kubectl version --client
