name: Proof

on:
  push:
    branches: 
      - develop

jobs:
  deploy:
    name: Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check tools
      run: |
        java -version
        mvn -version
        aws --version
        kubectl version --client
        eksctl version
